Implement runbook demo api and endpoints
seecloud/ceagle pull request #58
Opened 2016-12-12 15:10 UTC by teferi

2016-12-19 17:26 UTC, maretskiy requested changes

2016-12-19 17:26 UTC, maretskiy commented on ceagle/api_fake_data/fake_runbooks.py
> +        "date": datetime.datetime.now(),
i guess that .isoformat() is missed

2016-12-19 17:26 UTC, maretskiy commented on ceagle/api_fake_data/fake_runbooks.py
> +        "date": datetime.datetime.now(),
Also, key name "date" looks inconsistent with the value, since value is date+time, however key "date" usually is used for YYY-dd-mm only

2016-12-19 17:26 UTC, maretskiy commented on raml/abao_hooks.js
> +var correct_runbook = {description: "test", name: "test", runbook: "test", type: "test"}
I would recommend to use same naming style within the file - mixedCase (like at L4-7):

    var bodyRunbook = { ... }  // correct runbook
    var bodyBadRunbook = { ... }

2016-12-19 17:26 UTC, maretskiy commented on raml/abao_hooks.js
> +  test.request.params.runbook_id = "123"
Both run_id and runbook_id can be added once at L4

2016-12-19 17:26 UTC, maretskiy commented on tests/unit/test.py
> +        # there should be no content on delete method
This is strange, because fake_runbooks.py:74 returns returns "{}":

     flask.jsonify({}), 204

2016-12-19 17:45 UTC, teferi commented on ceagle/api_fake_data/fake_runbooks.py
> +        "date": datetime.datetime.now(),
true, also would replace them with started_at & finished_at

2016-12-19 17:45 UTC, teferi commented on raml/abao_hooks.js
> +var correct_runbook = {description: "test", name: "test", runbook: "test", type: "test"}
done

2016-12-19 17:45 UTC, teferi commented on raml/abao_hooks.js
> +  test.request.params.runbook_id = "123"
done

2016-12-19 17:46 UTC, teferi commented on tests/unit/test.py
> +        # there should be no content on delete method
looks like flask ignores any content for 204 responses. (NO_CONTENT =))

2016-12-20 09:46 UTC, Cesarsar commented on raml/api.raml
> +    /runbooks:
Could you please add response examples? At least for GET api calls with 200 response status.

2016-12-20 13:34 UTC, teferi commented on raml/api.raml
> +    /runbooks:
Done

2016-12-20 14:45 UTC, maretskiy commented on ceagle/api_fake_data/fake_runbooks.py
> +    finished_at = (datetime.datetime.now() + datetime.timedelta(
Not critical for fake data, however this is strange to have finished_at in future.
It is more logical to have finished_at == ...now(), started_at = finished_at - timedelta(...)

2016-12-20 14:45 UTC, maretskiy approved these changes

2016-12-23 12:23 UTC, Cesarsar requested changes

2016-12-23 12:23 UTC, Cesarsar commented on raml/response_examples/200/runbook_runs.json
> +			"started_at": "2016-12-20T16:18:42.150142",
This time format differs of time that comes from /api/v1/status/availability/day, for example: "2016-12-22T00:00"
We need to use the same format.

2016-12-26 10:02 UTC, teferi commented on raml/response_examples/200/runbook_runs.json
> +			"started_at": "2016-12-20T16:18:42.150142",
What you're saying is we don't need seconds and mseconds in the format? I don't think it's a good idea

2016-12-29 22:28 UTC, boris-42 commented
@teferi please rebase this patch

2016-12-30 10:12 UTC, Cesarsar approved these changes

2016-12-31 01:07 UTC, boris-42 approved these changes

2016-12-31 01:08 UTC, merged